version: '3.9'

services:
  php-env:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 8090:80

  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9010:80
    environment:
      - PMA_ARBITRARY=1

  mail:
    image: schickling/mailcatcher:latest
    container_name: project_mail
    networks:
      - default
    environment:
      - VIRTUAL_HOST=mail.project.docker
      - VIRTUAL_PORT=1080
